{
    "<p>A basic text field</p>": "<p>A basic text field</p>",
    "<p>Specify false to validate that the value's length must be &gt; 0. If <code>true</code>, then a blank value is <strong>always</strong> taken to be valid regardless of any {@link #vtype}\nvalidation that may be applied.</p>\n<p>If {@link #vtype} validation must still be applied to blank values, configure {@link #validateBlank} as <code>true</code>;</p>": "<p>Specify false to validate that the value's length must be &gt; 0. If <code>true</code>, then a blank value is <strong>always</strong> taken to be valid regardless of any {@link #vtype}\nvalidation that may be applied.</p>\n<p>If {@link #vtype} validation must still be applied to blank values, configure {@link #validateBlank} as <code>true</code>;</p>",
    "<p>The default text to place into an empty field</p>": "<p>The default text to place into an empty field</p>",
    "<p>Error text to display if the <strong>{@link #minLength minimum length}</strong> validation fails.</p>": "<p>Error text to display if the <strong>{@link #minLength minimum length}</strong> validation fails.</p>",
    "<p>Error text to display if the <strong>{@link #maxLength maximum length}</strong> validation fails</p>": "<p>Error text to display if the <strong>{@link #maxLength maximum length}</strong> validation fails</p>",
    "<p>True to set the maxLength property on the underlying input field. Defaults to false</p>": "<p>True to set the maxLength property on the underlying input field. Defaults to false</p>",
    "<p>A JavaScript RegExp object to be tested against the field value during validation.\nIf the test fails, the field will be marked invalid using\neither <strong>{@link Text#regexText}</strong> or <strong>{@link Text#invalidText}</strong>.</p>": "<p>A JavaScript RegExp object to be tested against the field value during validation.\nIf the test fails, the field will be marked invalid using\neither <strong>{@link Text#regexText}</strong> or <strong>{@link Text#invalidText}</strong>.</p>",
    "<p>The error text to display if <strong>{@link Text#regex}</strong> is used and the test fails during validation</p>": "<p>The error text to display if <strong>{@link Text#regex}</strong> is used and the test fails during validation</p>",
    "<p>Sets the default text to place into an empty field</p>": "<p>Sets the default text to place into an empty field</p>",
    "<p>Validates a value according to the field's validation rules and returns an array of errors\nfor any failing validations.</p>": "<p>Validates a value according to the field's validation rules and returns an array of errors\nfor any failing validations.</p>",
    "<p>The value to validate. The processed raw value will be used if nothing is passed.</p>": "<p>The value to validate. The processed raw value will be used if nothing is passed.</p>",
    "<p>Array of any validation errors</p>": "<p>Array of any validation errors</p>"
}