{
    "<p>A basic labeled form field</p>": "<p>基础的有标记的表单字段</p>",
    "<p>The width of the {@link Label#fieldLabel} in pixels. Only applicable if {@link Label#labelAlign}\nis set to &quot;left&quot; or &quot;right&quot;.</p>": "<p>以像素为单位的{@link Label#fieldLabel}的宽。只有在{@link Label#labelAlign}被设置为&quot;left&quot;或者&quot;right&quot;时。</p>",
    "<p>Controls the position and alignment of the {@link Label#fieldLabel}. Valid values are:</p>\n<ul>\n<li><code>left</code> (the default) - The label is positioned to the left of the field, with its text aligned to the left. Its width is determined by the {@link Label#labelWidth} config.</li>\n<li><code>top</code> - The label is positioned above the field.</li>\n<li><code>right</code> - The label is positioned to the left of the field, with its text aligned to the right. Its width is determined by the {@link Label#labelWidth} config.</li>\n</ul>": "<p>控制{@link Label#fieldLabel}的位置和对齐。可用的值有：</p><ul><li><code>left</code> (默认值) - 标签被放置在字段的左边，并且文字左对齐。它的宽由{@link Label#labelWidth}配置决定。</li><li><code>top</code> - 标签被放置在字段的上面。</li><li><code>right</code> - 标签被放置在字段的右边，并且文字右对齐。它的宽由{@link Label#labelWidth}配置决定。</li></ul>",
    "<p>The location where the error message text should display. Must be one of the following values:</p>": "<p>错误信息文字显示的位置。必须是一下其中之一的值：</p>",
    "<ul>\n<li><code>title</code> Display the message in a default browser title attribute popup.</li>\n<li><code>under</code> Add a block div beneath the field containing the error message.</li>\n<li><code>side</code> Add an error icon to the right of the field, displaying the message in a popup on hover.</li>\n</ul>": "<ul><li><code>title</code> 在浏览器默认的titie属性弹窗里显示信息。</li><li><code>under</code> 在字段的下方添加一个包含错误信息的块级div。</li><li><code>side</code> 在字段的右侧添加一个错误图标，在悬停的弹窗里显示信息。</li></ul>",
    "<p>Character(s) to be inserted at the end of the {@link Label#fieldLabel label text}. Set to empty string to hide the separator completely.</p>": "<p>插入到{@link Label#fieldLabel 标签文字}结束处的符号。设置为空字符串将分隔符完全隐藏。</p>",
    "<p>determined by the {@link Label#labelAlign} and {@link Label#labelWidth} configs.</p>": "<p>由{@link Label#labelAlign}和{@link Label#labelWidth}的设置决定。</p>",
    "<p>Tells whether the field currently has an active error message. This does not trigger validation on its own, it\nmerely looks for any message that the component may already hold.</p>": "<p>表示字段当前是否有激活的错误信息。这不会触发自身的校验，它仅仅查找组件已经具有的任何信息。</p>",
    "<p>Gets an Array of any active error messages currently applied to the field. This does not trigger validation on\nits own, it merely returns any messages that the component may already hold.</p>": "<p>获取当前任何应用于该字段的错误信息。这不会触发自身的校验，它仅返回组件可能已经有的任何信息。</p>",
    "<p>The active error messages on the component; if there are no errors, an empty Array is\nreturned.</p>": "<p>组件当前的错误信息；如果没有，返回空数组。</p>",
    "<p>Returns the label for the field. Defaults to simply returning the {@link #fieldLabel} config. Can be overridden\nto provide a custom generated label.</p>": "<p>返回该字段的标签。默认只返回{@link #fieldLabel}配置。可以重写以提供自定义生成的标签。</p>",
    "<p>The configured field label, or empty string if not defined</p>": "<p>配置的标签，如果未定义，则为空字符串。</p>",
    "<p>Returns the trimmed label by slicing off the label separator character. Can be overridden.</p>": "<p>返回去掉了标签分隔符后被修正过的标签。可以重写。</p>",
    "<p>The trimmed field label, or empty string if not defined</p>": "<p>修整后的字段标签，如果未定义，则为空字符串。</p>",
    "<p>The label for the field. It gets appended with the {@link Label#labelSeparator}, and its position and sizing is\ndetermined by the {@link Label#labelAlign} and {@link Label#labelWidth} configs.</p>": "<p>字段的标记。和{@link Label#labelSeparator}，以及其位置和尺寸一起被添加。</p>"
}